spring:
  datasource:
    url: jdbc:mysql://db.club012.com:3306/vibe_db
    username: ${DB_USERNAME:vibe_user}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: db.club012.com
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
